### ISSUE TITLE
ErrorException: Non-static method Rap2hpoutre\LaravelLogViewer\LaravelLogViewer::all() should not be called statically  in /Users/xxxx/Sites/statamicxxxx/site/addons/PowerTools/PowerToolsController.php:54

### ISSUE THREAD

**Issue by ebeauchamps** [edalzell/statamic-powertools#18] opened 2018-10-19 16:59 UTC
Can provide the stack trace if necessary.
Statamic latest 2.10.7
updated Powertools to latest as of today and got this in the logs

**Comment by edalzell** [comment] 2018-10-19 17:01
I don't call it statically, are you sure you're on the latest version of Powertools?

https://github.com/edalzell/statamic-powertools/blob/master/PowerTools/PowerToolsController.php#L54

**Comment by ebeauchamps** [comment] 2018-10-31 21:36
yes sir, just downloaded it after upgrading to 2.10.7. This error was displayed once.

**Comment by edalzell** [comment] 2019-02-22 06:21
This still an issue @ebeauchamps ?

**Comment by ebeauchamps** [comment] 2019-02-23 22:20
Will have to try again soon. I'll tell you

**Comment by edalzell** [comment] 2019-03-06 19:05
closed to do lack of response

**Comment by alehandrof** [comment] 2020-03-28 17:43
I'm also getting this error message and can help troubleshoot it:

```
ErrorException in PowerToolsController.php line 54:
Non-static method Rap2hpoutre\LaravelLogViewer\LaravelLogViewer::all() should not be called statically
```

**Comment by edalzell** [comment] 2020-03-28 17:44
> Can you please find `PowerToolsController.php` and paste line 54 in here @ebeauchamps ?

@alehandrof ^^^

**Comment by ebeauchamps** [comment] 2020-03-28 17:48
Hello @edalzell 
Sorry, but I decided not to use Powertools anymore. So I can help much I guess.
Take care.

**Comment by alehandrof** [comment] 2020-03-28 17:49
@edalzell:

```
        $data = [
            'logs' => LaravelLogViewer::all(),
            'files' => LaravelLogViewer::getFiles(true),
            'current_file' => LaravelLogViewer::getFileName(),
            'action_path' => route('logs'),
        ];
```

Line 54 in the file is 2nd line in my snippet.

**Comment by edalzell** [comment] 2020-03-28 19:11
right different than what's in the code: 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/6069653/77831586-4d9e4700-70ed-11ea-9f29-0d439375e69a.png">

**Comment by edalzell** [comment] 2020-03-28 19:14
@alehandrof what version are you using? Can you try the most current release?

**Comment by alehandrof** [comment] 2020-04-02 07:54
The issue is resolved in the most recent release. Apologies for the false alarm! 🙏

**Closed** 2020-04-02 13:44 UTC
Labels: waiting
